version: 0.2

phases:

  pre_build:
    commands:
      - echo Logging into ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 053849129210.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - docker build -t brain-tasks-app .
      - docker tag brain-tasks-app:latest 053849129210.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest

  post_build:
    commands:
      - docker push 053849129210.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest

artifacts:
  files:
    - deployment.yaml
    - service.yaml
